### ISSUE TITLE
文档计划

### ISSUE THREAD

**Issue by caoxiemeihao** [electron-vite/docs#1]
背景：

1. 这个仓库(docs)开了一段时间了，最初计划出完整文档；后来因为各种原因一直搁置了。
2. 目前 (2022-08-07 PM) `electron-vite-vue` 与 `cawa-93/vite-electron-builder` 还仅剩一个 ⭐️ 之差。
3. `electron-vite-vue`  的上手难度已经尽量做到 “开箱即用” 了，当然肯定还有优化空间。
4. 鉴于之前在知乎上发过两篇文章些 Vite + Electron 的整合，评论区有几个人希望后续深入的文档。
5. 所以计划提供一份完整的、深入原理的全方位文档。
6. 现实中我想做的东西有点小多(尽管我已经投入了周六日)，精力不够用(还要搬砖的)；思来想去，打算好好维护下去这个组织。
7. 各路大佬意下如何 🥺

@watonyweng @yi-Xu-0100

**Comment by caoxiemeihao** [comment]
目前零零散散写了一部分，放在了 [electron-vite/docs/docs](https://github.com/electron-vite/docs/tree/main/docs) 下面(暂时找了个地方放 😅)

**Comment by yi-Xu-0100** [comment]
@caoxiemeihao 我本人只能做一些 action 流程和一些细枝末节的帮助，不会深入的技术部分😅，我看到能够改善的地方，会帮忙提交PR。

想知道，准备用什么方式给出文档站点，静态站点生成器选择什么？或者需要参考什么？

**Comment by caoxiemeihao** [comment]
想着先发几个小节到知乎上看看阅读量，慢慢再知乎发完
阅读量要是大了起来，考虑那种免费的静态网站部署下。静态网站主要考虑可能会出英文版本的

**Comment by yi-Xu-0100** [comment]
@caoxiemeihao 我当时搜索 vite + electron + vue3 找到的新的方案就是大佬你在知乎的回答，然后过来看看的，非常棒！期待大佬发布更多的解析和说明！

**Comment by caoxiemeihao** [comment]
原来是知乎过来的 😂

**Comment by caoxiemeihao** [comment]
文档已经开始！[知乎专栏《Electron ⚡️ Vite》](https://www.zhihu.com/column/c_1553415231476269056) :)

**Comment by watonyweng** [comment]
@caoxiemeihao @yi-Xu-0100 立马关注起来，Vite 使 Electron 更丝滑

**Comment by RSS1102** [comment]
induce  [electron-vite-vue](https://github.com/electron-vite/electron-vite-vue) issue,to organize within the document
- [x] sqlite3,serialport或者其他C++插件,c#等插件。
- [ ] https://github.com/electron-vite/electron-vite-vue/issues/52
- [ ] sourcemap的问题（要具体了解）: https://github.com/electron-vite/electron-vite-vue/issues/61
- [ ] 部分问题集合: https://github.com/electron-vite/electron-vite-vue/issues/71
- [ ] 如何使用electron原生api https://github.com/electron-vite/electron-vite-vue/issues/66
- [ ] 出口未定义： https://github.com/electron-vite/electron-vite-vue/issues/103#issuecomment-1098662928
-  https://github.com/electron-vite/electron-vite-vue/issues/105
- [ ] https://github.com/electron-vite/electron-vite-vue/issues/112
- [ ] https://github.com/electron-vite/electron-vite-vue/issues/163
- https://github.com/electron-vite/electron-vite-vue/issues/169
- [ ] https://github.com/electron-vite/vite-plugin-electron/issues/13
- https://github.com/electron-vite/electron-vite-vue/issues/191
- [x] https://github.com/electron-vite/electron-vite-vue/issues/290
- [x] https://github.com/electron-vite/electron-vite-vue/issues/281
- [x] https://github.com/electron-vite/electron-vite-vue/issues/272
- [x] https://github.com/electron-vite/electron-vite-vue/issues/339
- [x] https://github.com/electron-vite/electron-vite-vue/issues/357
- [x] https://github.com/electron-vite/electron-vite-vue/issues/353

**Comment by RSS1102** [comment]
induce [electron-vite-react](https://github.com/electron-vite/electron-vite-react)issue,to organize within the document
- [ ] https://github.com/electron-vite/electron-vite-react/issues/62
- [x] https://github.com/electron-vite/electron-vite-react/issues/126
- [x] https://github.com/electron-vite/electron-vite-react/issues/140
- [x] https://github.com/electron-vite/electron-vite-react/issues/37

**Comment by RSS1102** [comment]
induce  [vite-plugin-electron](https://github.com/electron-vite/vite-plugin-electron)  issue,to organize within the document
- [x] https://github.com/electron-vite/vite-plugin-electron/issues/17
-  https://github.com/electron-vite/vite-plugin-electron/issues/23

---

induce [vite-plugin-electron-renderer](https://github.com/electron-vite/vite-plugin-electron-renderer) issue,to organize within the document
- [x] https://github.com/electron-vite/vite-plugin-electron-renderer/issues/31

**Comment by RSS1102** [comment]
close by [electron-vite.github.io](https://electron-vite.github.io/)
