### ISSUE TITLE
Typo on Why Electron-Vite Page

### ISSUE THREAD

**Issue by nsdeschenes** [electron-vite/docs#32]
Was taking a peak at this page and I believe there is a typo on this page as the wording is a bit confusing:

At the same time, **Electron-Vite is a Vite is a very important** part of the Electron and Vite community ecosystem, and is meant to provide a complete, simple, out-of-the-box Electron development experience based on Vite.

**Comment by caoxiemeihao** [comment]
Thanks for your feedback my English is poor, and I'm trying hard to learn English 😅

**Comment by nsdeschenes** [comment]
Haha no problem at all! If you have any question let me know 🙂

**Comment by caoxiemeihao** [comment]
I would appreciate it if you could raise a PR for the typo. I will keep the origin Chinese text under each paragraph.
